// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEzRjGdPpM9SeehcCEHp5G1_JRVYcblc',
    appId: '1:275313479574:web:a268da49313ed262f097b7',
    messagingSenderId: '275313479574',
    projectId: 'voczilla-d2d79',
    authDomain: 'voczilla-d2d79.firebaseapp.com',
    storageBucket: 'voczilla-d2d79.firebasestorage.app',
    measurementId: 'G-NJZMFG8XRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACEQiRIO3D6RhTcl5NGzn_ugpWSHbYPt4',
    appId: '1:275313479574:android:3bd69b3ea9bbb8f3f097b7',
    messagingSenderId: '275313479574',
    projectId: 'voczilla-d2d79',
    storageBucket: 'voczilla-d2d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBYGY_ZvuMQdezn1LXtdroeUucIefG3U',
    appId: '1:275313479574:ios:d4f902f8d95eb429f097b7',
    messagingSenderId: '275313479574',
    projectId: 'voczilla-d2d79',
    storageBucket: 'voczilla-d2d79.firebasestorage.app',
    androidClientId: '275313479574-n7og0bhk14ib7j43gipmkpe6r9bvuj4p.apps.googleusercontent.com',
    iosClientId: '275313479574-kprstmafer4av3da9lsu3dh7insd2v7m.apps.googleusercontent.com',
    iosBundleId: 'com.geoffreypetain.voczilla.voczilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmBYGY_ZvuMQdezn1LXtdroeUucIefG3U',
    appId: '1:275313479574:ios:35a45c028faef827f097b7',
    messagingSenderId: '275313479574',
    projectId: 'voczilla-d2d79',
    storageBucket: 'voczilla-d2d79.firebasestorage.app',
    androidClientId: '275313479574-n7og0bhk14ib7j43gipmkpe6r9bvuj4p.apps.googleusercontent.com',
    iosClientId: '275313479574-lsdoe1bc971qptt77hdgtudperq53m8i.apps.googleusercontent.com',
    iosBundleId: 'com.geoffreypetain.voczilla.vobzilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXEzRjGdPpM9SeehcCEHp5G1_JRVYcblc',
    appId: '1:275313479574:web:8e9f6749a05ce00ff097b7',
    messagingSenderId: '275313479574',
    projectId: 'voczilla-d2d79',
    authDomain: 'voczilla-d2d79.firebaseapp.com',
    storageBucket: 'voczilla-d2d79.firebasestorage.app',
    measurementId: 'G-MS1ZXRCZBZ',
  );

}