# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# Fastfile

platform :ios do
  # Description de la lane beta
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ios/Runner.xcodeproj")
    build_app(workspace: "ios/Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  # Lane pour capturer les captures d'écran
  lane :capture_screenshots do
    snapshot(
      workspace: "ios/Runner.xcworkspace", # Chemin vers votre fichier .xcworkspace
      scheme: "Runner"                     # Nom du scheme que vous souhaitez utiliser
    )
  end
end
